// import type { Metadata } from 'next'
// import './globals.css'
// import ThemeRegistry from '../../app/components/ThemeRegistry'
// import { PostProvider } from '../../contexts/PostContext'

// export const metadata: Metadata = {
//     title: 'Next App MUI',
//     description: 'Generated by create next app',
// }

// export default function RootLayout({
//     children,
// }: {
//     children: React.ReactNode
// }) {
//     return (
//         <html lang="en">
//             <ThemeRegistry>
//                 <PostProvider>
//                     <body>{children}</body>
//                 </PostProvider>
//             </ThemeRegistry>

//         </html>
//     )
// }